### PR TITLE
Updates to latest wazero

### PR DESCRIPTION
**Pull request by codefromthecrypt**
We continue to improve the API and now it defaults to JIT.

### CODE REVIEW

**Comment by wuhuizuo** [comment]
thanks @codefromthecrypt could you fix or reply for the naming suggestions?

**Comment by codefromthecrypt** [comment]
yes I will re-update this soon!

**Comment by codefromthecrypt** [comment]
working on this now, and will push tomorrow!

**Comment by codefromthecrypt** [comment]
actually I think i got it except wasmedge dependencies seem to make my IDE unable to work. maybe you can check that part and merge when ready. Thanks!

PS almost all threading issues are resolved, so worth trying to use wazero multi-threaded I think.

**Pull request merged**
