### PR TITLE
wazero: updates to latest API

### PR DESCRIPTION
**Pull request by codefromthecrypt**
See https://github.com/tetratelabs/wazero/pull/427

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
ps I tried to update the plugins, but I don't use docker desktop due to licensing issues. I use lima instead and it errors due to the need to write-back to the host FS

```
go build github.com/wuhuizuo/go-wasm-go/provider/plugin/ok: copying /tmp/go-build59953869/b001/exe/a.out.so: open plugin-1.16.15.so: read-only file system
```

**Comment by wuhuizuo** [comment]
Should not commit the wasm binary file, ci pipeline will build it before testing.
@codefromthecrypt

**Comment by wuhuizuo** [comment]
Pls rebase it to solve dependency conflict

**Comment by wuhuizuo** [comment]
I tried to solve the merge conflict, but occur the ci build failing

**Comment by codefromthecrypt** [comment]
OK 🤞

**Pull request merged**
